#### CSE 452: Neural Networks and Fuzzy Systems Lab
Summer-2020, Dept. of CSE, NEUB <br>

#### Student Info
<b>Name:</b> Gulam Kibria Chowdhury<br>
<b>Reg. No:</b> 170103020033

## Assignment 3: Hopfield

$$ dw=x.x^T -I \space \space \\ where \space \space I =\space identity \space matrix.$$  
$$w=w+dw$$

<b>Energy</b>
$$E=\frac{−1}{2} \sum_{j=1}^n  \sum_{i=1}^n w_{ij}x_i x_j$$

In terms of linear algebra, simpler version is 
$$E = -\frac{1}{2} x^T.W.x$$

In [1]:
import numpy as np  
import matplotlib.pyplot as plt   

In [2]:
#Neurons=9
N=9

In [3]:
x1=np.array([1,1,1, 0,0,0, 0,0,0])
x2=np.array([0,0,0, 0,0,0, 1,1,1])
x3=np.array([0,0,0, 1,1,1, 0,0,0])

In [4]:
w=np.zeros((N,N))
print(w)

[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]


<b>Task 1: Train x1</b>
Train x1 and update w and calculate energy.<br>
<b>updated w</b> should look like the following. <br>
       [ 0.,  1.,  1., -1., -1., -1., -1., -1., -1.],<br>
       [ 1.,  0.,  1., -1., -1., -1., -1., -1., -1.],<br>
       [ 1.,  1.,  0., -1., -1., -1., -1., -1., -1.],<br>
       [-1., -1., -1.,  0.,  1.,  1.,  1.,  1.,  1.],<br>
       [-1., -1., -1.,  1.,  0.,  1.,  1.,  1.,  1.],<br>
       [-1., -1., -1.,  1.,  1.,  0.,  1.,  1.,  1.],<br>
       [-1., -1., -1.,  1.,  1.,  1.,  0.,  1.,  1.],<br>
       [-1., -1., -1.,  1.,  1.,  1.,  1.,  0.,  1.],<br>
       [-1., -1., -1.,  1.,  1.,  1.,  1.,  1.,  0.]]<br>
       
energy should be=-36

In [5]:
#your code goes here.
x1[x1==0]=-1
print("x1: \n",x1,"\n")
x1_T=x1.reshape(-1, 1)
print("x1_T: \n",x1_T,"\n")
new_w=(x1*x1_T)
for i in range(0,len(x1)):
    new_w[i][i]=0

w=w+new_w

print("Upadate W: \n",w)

xx=np.dot(w,x1.T)
E=np.dot(xx,x1)*(-0.5)
print("\nEnergy =",E)


x1: 
 [ 1  1  1 -1 -1 -1 -1 -1 -1] 

x1_T: 
 [[ 1]
 [ 1]
 [ 1]
 [-1]
 [-1]
 [-1]
 [-1]
 [-1]
 [-1]] 

Upadate W: 
 [[ 0.  1.  1. -1. -1. -1. -1. -1. -1.]
 [ 1.  0.  1. -1. -1. -1. -1. -1. -1.]
 [ 1.  1.  0. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1.  0.  1.  1.  1.  1.  1.]
 [-1. -1. -1.  1.  0.  1.  1.  1.  1.]
 [-1. -1. -1.  1.  1.  0.  1.  1.  1.]
 [-1. -1. -1.  1.  1.  1.  0.  1.  1.]
 [-1. -1. -1.  1.  1.  1.  1.  0.  1.]
 [-1. -1. -1.  1.  1.  1.  1.  1.  0.]]

Energy = -36.0


# Task_1 complete ...................

<b>Task 2: Train x2</b>
Train x2 and update w and calculate energy.<br>

In [6]:
#your code goes here.

x2[x2==0]=-1
print("x2: \n",x2,"\n")
x2_T=x2.reshape(-1, 1)
print("x2_T: \n",x2_T,"\n")
new_w=(x2*x2_T)
for i in range(0,len(x2)):
    new_w[i][i]=0

w=w+new_w

print("Upadate W: \n",w)

xx=np.dot(w,x2.T)
E=np.dot(xx,x2)*(-0.5)
print("\nEnergy =",E)

x2: 
 [-1 -1 -1 -1 -1 -1  1  1  1] 

x2_T: 
 [[-1]
 [-1]
 [-1]
 [-1]
 [-1]
 [-1]
 [ 1]
 [ 1]
 [ 1]] 

Upadate W: 
 [[ 0.  2.  2.  0.  0.  0. -2. -2. -2.]
 [ 2.  0.  2.  0.  0.  0. -2. -2. -2.]
 [ 2.  2.  0.  0.  0.  0. -2. -2. -2.]
 [ 0.  0.  0.  0.  2.  2.  0.  0.  0.]
 [ 0.  0.  0.  2.  0.  2.  0.  0.  0.]
 [ 0.  0.  0.  2.  2.  0.  0.  0.  0.]
 [-2. -2. -2.  0.  0.  0.  0.  2.  2.]
 [-2. -2. -2.  0.  0.  0.  2.  0.  2.]
 [-2. -2. -2.  0.  0.  0.  2.  2.  0.]]

Energy = -36.0


# Task_2 complete ...................

<b>Task 3: Train x3</b>
Train x3 and update w and calculate energy.<br>

In [7]:
#your code goes here.

x3[x3==0]=-1
print("x3: \n",x3,"\n")
x3_T=x3.reshape(-1, 1)
print("x3_T: \n",x3_T,"\n")
new_w=(x3*x3_T)
for i in range(0,len(x3)):
    new_w[i][i]=0

w=w+new_w

print("Upadate W: \n",w)

xx=np.dot(w,x3.T)
E=np.dot(xx,x3)*(-0.5)
print("\nEnergy =",E)

x3: 
 [-1 -1 -1  1  1  1 -1 -1 -1] 

x3_T: 
 [[-1]
 [-1]
 [-1]
 [ 1]
 [ 1]
 [ 1]
 [-1]
 [-1]
 [-1]] 

Upadate W: 
 [[ 0.  3.  3. -1. -1. -1. -1. -1. -1.]
 [ 3.  0.  3. -1. -1. -1. -1. -1. -1.]
 [ 3.  3.  0. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1.  0.  3.  3. -1. -1. -1.]
 [-1. -1. -1.  3.  0.  3. -1. -1. -1.]
 [-1. -1. -1.  3.  3.  0. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1.  0.  3.  3.]
 [-1. -1. -1. -1. -1. -1.  3.  0.  3.]
 [-1. -1. -1. -1. -1. -1.  3.  3.  0.]]

Energy = -36.0


# Task_3 complete ...................

<b>Task 4: Asynchronous recovery</b> <br>
tx=np.array([0,0,0, 1,0,0, 0,0,0])  <br>

1. choose i randomly
2. update ith element of partial pattern tx 
3. Repeat step 2 for some time.

$$x_i=sign(w_i.x)$$

It should converge to a known pattern <br>[0, 0, 0, 1, 1, 1, 0, 0, 0]

In [8]:
#your code goes here.

def activate(val):
        if val>=0:
            return 1
        else:
            return -1

def SUM(k,h):
    val=0
    for i,j in zip(k,h):  
        val=val+(i*j)
    return val   
def check(xx,yy):
    f=0
    for i,j in zip(xx,yy):
        if(i==j):
            f+=1
    if(f==len(xx)):
        return 1
    else:
        return 0


from random import randrange
tx=np.array([0,0,0, 1,0,0, 0,0,0])
tx[tx==0]=-1
#print(tx)
while True:
    if(check(tx,x1)):  
        break
    elif(check(tx,x2)): 
        break
    elif(check(tx,x3)): 
        break
    rnd=randrange(len(tx))
    #print(rnd)
    summ=SUM(w[rnd],tx);
    #print(summ)
    tx[rnd]=activate(summ)
    #print(rnd,tx[rnd])
    #print(tx)
    
tx[tx==-1]=0
print("Recovery The pattern :\n",tx)

Recovery The pattern :
 [0 0 0 1 1 1 0 0 0]


# Task_4 complete ...................